# Install and configure Bacul-client on Windows
---

- name: Install Bacula package on Windows
  win_chocolatey:
    name: bacula
    state: present

- name: import bacula template
  win_template:
    src: 'bacula-fd.conf.j2'
    dest: 'C:\Program Files\Bacula\bacula-fd.conf'
  notify:
    - "(Handler: All Windows OSs) Restart bacula-fd"

- name: Manage bacula-fd service
  win_service:
    name: Bacula-fd
    state: started
    start_mode: auto
